apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodflow-app
spec:
  template:
    spec:
      containers:
        - name: foodflow-app
          # Updated by CI/CD pipeline
          image: ghcr.io/simonbrundin/foodflow@sha256:97466a996c31c4654d72429a6c760a3beccd62c9b1d28e618b073820aedfc675
          env:
            - name: NODE_ENV
              value: "production"
            - name: NUXT_PUBLIC_APP_URL
              value: "https://foodflow.simonbrundin.com"
            - name: NUXT_PUBLIC_API_URL
              value: "https://foodflow.simonbrundin.com/api"
