apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodflow-app
spec:
  template:
    spec:
      containers:
        - name: foodflow-app
          # Updated by CI/CD pipeline
          image: ghcr.io/simonbrundin/foodflow:ff9dd4bac6f1a8b260972f7347fa0c4a8d43d842
          env:
            - name: NODE_ENV
              value: "production"
            - name: NUXT_PUBLIC_APP_URL
              value: "https://foodflow.simonbrundin.com"
            - name: NUXT_PUBLIC_API_URL
              value: "https://foodflow.simonbrundin.com/api"
