apiVersion: ENC[AES256_GCM,data:mhQ=,iv:B5ZAo0Y4m4A8uRvAyfwRjnwtD/IufinIL3kmzrDA1JM=,tag:AVekGhvDwOQJuKjiGjp4Vg==,type:str]
kind: ENC[AES256_GCM,data:lJ0+iSB7,iv:aaIZBa9nawu+GHSJYrApCTW+TAooKFHmWSoeUgsZd+A=,tag:p+xgNl0J9J7LXTdK6fvawg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+BnIafL7RhabRrRSd/XRjoQ=,iv:pJevDwGNxQbgDpNxOO+voiyx/u1e9b2qq/d9W1WxnPQ=,tag:RrgelYvhyCqOShK5Sv4LIA==,type:str]
    namespace: ENC[AES256_GCM,data:RTy12F6cOD8=,iv:0aKFE3IbyPIs8aVlBQs2UHEWHUNZ+YDRtbNELFpRd04=,tag:HAlmQ0KKkVTYZ5+MDRmE4w==,type:str]
    labels:
        cnpg.io/reload: ENC[AES256_GCM,data:UUI+uw==,iv:xO0aCI+Apz/ZTdad2c95sIW/iCs7PoYT37ix5B572T8=,tag:REVKkB4nVQ+rQpjnUPfk2A==,type:str]
type: ENC[AES256_GCM,data:W8moc+X5,iv:BEuAC2MR4sTQPVSj7d4uzeYVXs6RLE6n2mKQF4Fu8Ps=,tag:d4fPUYgp00HmmjJRhMxq1A==,type:str]
stringData:
    password: ENC[AES256_GCM,data:MMlYTVRZp2+i5Kb7i4WWuQH8loh8fLuMIztaeskj/Yk=,iv:LcicGtwEAgbLwESeQI0aKDldP7RF0uCVLe1MhNoCKXk=,tag:ofztXQiDPIGn/7Q6/eeyFw==,type:str]
    username: ENC[AES256_GCM,data:weoJiJk=,iv:keE5gqklSsCowb1O21Ajnj9dEhi+Ivs6MaDegIjN9wQ=,tag:4neRvlSe6JYJNs65QBnYoA==,type:str]
    uri: ENC[AES256_GCM,data:FyTgLt6g2ehBUNDW64nzeK9yI0NJ2YaQwUxiMqsAddsPc15bYIkyUkHOy5y9PlR0NEUhAqPvVcy8qDGF08PkdL6Z3zpH69UNP7pxu/i8hNCyeDyNxwYoFEL2NQlOoXrfq6htpuqGUxf+/sC4IL0MbE38B6mTfuXMNFQt9E7g,iv:JfuYY2rCTbtjngq8oTtg+t/S9zLdObmzYRNJ6eEEO4o=,tag:1x5aLXp2bxlHqUHj/S8grw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeGpCL2ZvQ2F6UFA0dmFj
            dGMyYmlXTGgraW4waGtZSXY3T0RnMEdYSFFvClBTYUFoMEhYVW1LV1RkYlNVSWFi
            dEF4bU1IeVN5aFVDSHhsbnNjekZRUGMKLS0tIFp5NU1hbGpwK1NrQm04YlVZYWZZ
            RGNDU3hmaEc2WDdaRDlIdThlYzUyNEkKcmF+c5BANTeKYcYEHI6O0w1bvBaRrEJ6
            0d1RgLKPhAIDLztAFY5BTJcTSzrWIFtJ4ZQjf/B1nPLSM+YY9R+CIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    lastmodified: "2026-09-23T10:18:06Z"
    mac: ENC[AES256_GCM,data:eYomUptUnIP76ItgZ9fpJJ8Uff+CuSpllen4l7GMgqS0tbJH0bJAqDew/65DSYsMUjmY+WeZrXeQI3XWrfHfgzRCWkjFTn4Op6UVGILG1DXcwVDUVlJgm8m7dNVa3vsmf9LYBmfTWQ4ct31hKc2KIcEPORql9NMIuB6f5G6FrLs=,iv:yxt6YcoltMV3Wuv64/lE6ZStWwmtwfBPGnVpht2JJR8=,tag:i+hG/UByra4Jrw+X/mchXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
