apiVersion: v1
kind: Secret
metadata:
    name: foodflow-db-user
    namespace: foodflow
    labels:
        cnpg.io/reload: "true"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+934A63mjJ6SfmXmNzCYg9U4kETpP48XCOtH7I1zI0U=,iv:dTEW9CQAiRM2dDi/6mTGRl8Q5wbNIopFdcKmH8RFTv4=,tag:4IO4QP+z55DDBsIfHdOifA==,type:str]
    username: ENC[AES256_GCM,data:uGBkjWMxN00=,iv:NyP2dcqPAXt9C5Sge2i5OO8dGVSocGN7GCGhP7Jr5U4=,tag:i3dnR95/OZvHRSL13vls5g==,type:str]
    jdbc-uri: ENC[AES256_GCM,data:ngrfCoSA99/If82TIkDpR9GWSiY8aosmtrF4c7vJ5f3q1oYPI0Rr4ZFEAqqVkLeEoARAFm094EOOZe7AS/HAawgo/XWhZ1bkG2dwSCbZmVaUA8gbRe74msd3gRhHaXVMnom4dxSXlrwsHVA8dcHxrJNFbluTg0vjmNRoRG1wqeFi,iv:W7Mkoj9BrjS7YxsTcQOz9Z82fr9/jK0melD5ZCyxG7I=,tag:PyjEThJkYH3WTrh6MVJ03Q==,type:str]
    uri: ENC[AES256_GCM,data:KVqpw6K28dKmJfsJGxTCKtYcIi0BfW3oui+XF1/ZIhER/Z8VyzGCE5FjR4DIX0chUPlWdHogcfqmbnw+8GoGEiknirtbhp66AiVvsE8nPS4Fpc0VPZ/G0sUnVn017QZ1mGCA4WYYeujoqMuQ5pg=,iv:oyoFeMDr85funn+PFlC3Q6u8CGgzEoJFHupQHqYva1s=,tag:BcLybWKrMrQzYCNFE8g/fQ==,type:str]
    pgpass: ENC[AES256_GCM,data:SzytGeVZJ2D+5ir6kSU3ptPudjAeNRMFiyfy84MzSuMYv0V5Rr1H5jE8qFs5l9vhYBQWWGp1ZszdYzo6gOZbaIbQOILQZ8q1CVvb3VwmTHLjy/P/TpO501ROxJMsBG6T6Q==,iv:Gda2AqHnoz3kxw7xCaKn1zQ+1+9Qai1u5/yCcCvKVS4=,tag:LZh47ZvocoAzcSKn4gAYOQ==,type:str]
    host: ENC[AES256_GCM,data:f0s0/rHamjgU4cUS1SBSEi0fr0OwI0HqnI4Er5iwPcU7qQrz1tu04Do=,iv:FyMabiASoWPwBrIsLydPbZD074QwCehnmABBYzo5VzQ=,tag:00kSFLMDzQZ+k4j5zmhXPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYUh0YWIzZEVNTGVVa1Rw
            WmQ1N1FKSjFCemdycXhjSlczSjlUd1JEYkI4CnN3RnlYZG1yV2JGN1VPRjdqLytP
            Y1U4MlhRbEI1WWRhL3Fub2k2N1VLNTAKLS0tIEU0VXhLNk43THJQdGZJL3FNdThH
            ZjY0MEliNmFOODUyaDN6Zm1UQVdIWXcKQzoi/0KBWbn0WXIplKaOSaipBYWklH9N
            PjCF5it6lSCVoc8xAsVcxgOk2vGIswjwN63LxOtpxSIP9az+mjwySg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T10:31:07Z"
    mac: ENC[AES256_GCM,data:hF7MYKyXT7tsVnHR3HAS/ZLYbA4m3rgx3TvVXNZxBzj5rlqNHbV/3idywNycQwlq7yd+lA/uYmMf80DbBDMdn1690x/RNKQSIXXPUbTZf7SwPQwXdCMqBkQORfMUO0ErsO1SO7KP33HMSoKOfBa/EEAlSmzghAkkMz0PSHnuf7Y=,iv:ugE8FXB1Cwvlcb8kvCbLXMK9FZh8VtbrTbiii5lB5zQ=,tag:YRx42bE9fupQ+LK1clC9QA==,type:str]
    version: 3.13.3
