apiVersion: v1
kind: Secret
metadata:
    name: foodflow-db-admin
    namespace: foodflow
    labels:
        cnpg.io/reload: "true"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:E5zpVUBPlermDM9cVggdHDoir6oEuse8AAsYyjzHig4=,iv:rt7d94kp9bFAaJpd6h6Ld8t+t8p92o2acTx36O7GbCs=,tag:AC9wNDSB9tV0Z6karyeFlw==,type:str]
    username: ENC[AES256_GCM,data:sF8vC9w=,iv:GAu4lOAK1+uTpqtX505DQzOP0v269pL74TbIaJelyiY=,tag:N352Bf1PHzZ+DBUy/1Gnfw==,type:str]
    uri: ENC[AES256_GCM,data:OQCJCMfw0toJ/gmQcxMZhU63gT6Cps0kQPiD4abNLuXhz1NmcCL0Zctzq11UrqRAzj+rZ6qkOLuNbfPo2Zi8GRn0eNkgZDUiw/bL2BFexLroLK/A/STukR7JyHaGAY7sLtvAT0cDcHuhjmVSks/RMbeHGcOharXc5LaSC1O0,iv:cb40Jt3XnU+7vy+M4mOrmsgBV8YrEuw+F/c7y5QZ7jw=,tag:YhjbodX8isaS3RPDgMhcJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM20ySzRBZFVSWXp4OUNh
            QmpCVURGeW5LMGY1TEpzai95UmttTEVoTEI4CmJuS05PaGNjVEpRSm9uTUliY0pv
            M3hwcVh4aThXN2F3U0hMTHB3Wi81Uk0KLS0tIHB2aDVEcFdLdEZRMkZFSDBjNFlm
            eE9sNE02NWZVTnE3WDQvamJCc056aGMKUH6YwzAcSQZYVgBzDUhyoWJUE742pbsy
            T5V+OXhpqLIw2WDGh3OCQbhFXbek7iHlLJmg32HB4pXhHpW8mvdwfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T10:31:07Z"
    mac: ENC[AES256_GCM,data:d4ymSx3KATJiLI26ahw1PaH2uqZsAi1B8NxtoxIuq7BkhMlNCXWNk/++J12J4j1OJ21K7OxjuYwRBvN/vvDasMbGu45+wx60NlktTYOTQVUpN+TW88XAdJRCtFaCK8inhlrJl6PAu/b3BhDYP+E0eB/KOCqCBpie7NG0VPSmx68=,iv:Q8dEGSa6ployu9rlyElHP6juJHk7ctKmkmg2RpMOYuI=,tag:rWJgjV65OQe6PvJpuyvQqA==,type:str]
    version: 3.13.3
