apiVersion: ENC[AES256_GCM,data:AOk=,iv:G/KKSgsj+T/ne4UP8DpZI3ViBVavXm+RHUDibGf6rno=,tag:VpgvOl9Y2Fb2Ez7yLC62vg==,type:str]
kind: ENC[AES256_GCM,data:HWGgQepa,iv:ZoSWqQTZa3qfLRWjEM6/chu7G31vti4vm6SykGFjoIw=,tag:Wc8/2gpIYOzLxcrgM+T7Qw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yDDPxQ6xRVog4qiXflxWeQ==,iv:7jICdYVoS3jZxDAJJkSR0lKetoOpTfqhfusMma6ZTzw=,tag:FfiWxKLeM6Pcc+zA7Dgi4Q==,type:str]
    namespace: ENC[AES256_GCM,data:XnXgRZhmnMA=,iv:f/uagj9T7WGP5wzyxORlVtsbQGlHJLzyPJjTd3a26Mk=,tag:a3QgKjVSaDbUU3LZB6bNjg==,type:str]
    labels:
        cnpg.io/reload: ENC[AES256_GCM,data:NM7stA==,iv:uW3q9HV4H0dN24QupeoL0xkzvmF5MI2fquI7I0cQFjw=,tag:IGJ81u2SilsFdFhc5YggPg==,type:str]
type: ENC[AES256_GCM,data:rLYxci8w,iv:0vyhPCrU5cz2pvrpIozYKp/jk5TrX/QR8Y6B3zvgwB4=,tag:iOBpV7qxNrlfJEh0+FDCkw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:s9g8bpKvc/sA9DLh6Gg9WOEy4z2I2rcCEqXACRivPSY=,iv:Co4F7Q4fyFltgOf1ZxgdoPI82nGMVnrPp3OKCQDA1Ls=,tag:zRC+YwOBCIqdC7glaiQ28A==,type:str]
    username: ENC[AES256_GCM,data:m47B6os0XlY=,iv:uesmjcx02kYzUkPAoAe5OYIJ9ljMKjx7R64ZnMYIxm8=,tag:M/LyXldsgzNysHnbp49MPg==,type:str]
    jdbc-uri: ENC[AES256_GCM,data:ICSBqTZM+EG/98+P7hiXuKkf4FSlDFKYVdadvI0ufvnuqrFplbUrjYc0qeHBnW9PEQdd1YkPNK+pxdh0Savs2Xf/VqdqHUO6BVOtAMoUz9eayF9cqhoSu24NKKdEkcjiTvyxLx/QUWrYtbSy3nj8N2QehLEhbqBkTDP4zrudIOkL,iv:/rUUYYBlm0fiere6NxxILKZDMT5tIpKYibdfVYGQgB0=,tag:Daa8Jw5QYG+NpR2aBjt/Lg==,type:str]
    uri: ENC[AES256_GCM,data:TwZV+0do7HBB8jSVRjJ6yJ62MwsLyRdGMYoB7dNj2HENEF7mZenhmcDtQV6NCgMsI0MHcMTGSn/+ku1cV1RyRlL3kdToRBn3XgKuXLFux9nCoHUu9rZS7Rg/ehOVHS4aHjA2A8YVPeDXIGahrGg=,iv:P5h7EPESyeYvYfvocLgHePTbPhjxQbQ78BRDMTZwuhk=,tag:ctUx/BqIZga8ApCShxI4Ow==,type:str]
    pgpass: ENC[AES256_GCM,data:b9I9XLDBSGMf6WXCc5kGHufaogY1f0gZ40HjDpG4wyqsFwRjwX7tnlrvykwUN7ViniP2Q3DJ1s3ROXllms2AaFQkwHJrTaIBvkLMtks3uBWrdPOzGNfO/iu9Fo7Dnc8mFQ==,iv:SZ2a960BnQ3oAJEBm+LerLxDx7NSaxb0ZIQafLjht9E=,tag:QDV60CJLs5ZEkYRB0dOuyA==,type:str]
    host: ENC[AES256_GCM,data:ThbM4lXqtYgyaDHADY5xPNtCjUd8IGGP6sLAOgYcs4GjDEOrZs0VESI=,iv:ASBF6S+16AYUyQvPCDuFoM0hGifxYfTEwNSHdBcslX8=,tag:incR0i2gbqvtLzLlof1D2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbWFnbFBPSG8xbm0xMFND
            aUZjYzYzZGlld3pscE1SRVdjTU9ZTVozTGtRCjhQa0prR2JEYjZqU0xsaWZUSGdh
            LytLT2hBQWY2cVU2NTNFY0ZqeEJSZnMKLS0tIHk1V1Q4a2FUd2tidXphUDVXZXIr
            aUZsMTNhUjJZSVBvdW1qMzJYQndReUEKvqOG0WBokHKXFZxtnqv9xaNMF+gI9mHd
            qiA9x98tWSPcp4VlUPnx2Bt3lbRqwo9AUpLSzBkAq588lh67WorkGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    lastmodified: "2026-09-23T10:18:06Z"
    mac: ENC[AES256_GCM,data:ZV6kc7WAElfpKBW/cmi48MM7fIxby6rpMORoCVTj1CVbEvH77dfWdXvuhb/vWQh7ekGOR6XWMUijN86p7MEJXEGLvtZKwKkX2XItBiPt+FDiedYvieP/Rp7TSJlCx21oaw8fnYctzQFE7OxuSbd2oFWTJRFydUZGvq7voghC3/U=,iv:1vK/8TPat9Li+kp2wKjyij9dbOss2fvN0OnlwMS+2L8=,tag:botQgeZzpHK7ZGXVHAq1jw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
