# Template for foodflow-app secrets
apiVersion: v1
kind: Secret
metadata:
    name: foodflow-app-secrets
    namespace: foodflow
type: Opaque
stringData:
    NUXT_OAUTH_ZITADEL_CLIENT_ID: ENC[AES256_GCM,data:zIgyqtXxWa/2F8No7v1Kj3rwr+oFzg==,iv:VahOlgX8/D4LjNMKo27SCuWFyRx6SZqUVTbiMD1AygU=,tag:EoxA0oIpN9IQ/fQ59dRtsw==,type:str]
    NUXT_OAUTH_ZITADEL_DOMAIN: ENC[AES256_GCM,data:APX1lne4K2WJbRP1w54/qTz08D0m,iv:3gkd24ubG23/aIhK0FZNqxWjijMYTXkP+vupS+4pDjM=,tag:He126pf4ExlshuJKd+mxNg==,type:str]
    NUXT_OAUTH_ZITADEL_REDIRECT_URL: ENC[AES256_GCM,data:6eC4n2Wu/jN2ZrOBV7i7MWpjgB/ppcn95A==,iv:a5NsrlAuYiuGXPugXuCrQ3U0myYydWiihDQNkSgp0rQ=,tag:BDBAfj1u1VgwSJmALSw21g==,type:str]
    APP_URL: ENC[AES256_GCM,data:BGckM9PZoarKG0Xtt/TJ/zAVdd0=,iv:58msw8wmrtgxwhYFvwp6NhL/6JRaIfyxV9sqPcUxwMA=,tag:J+OIpOrlE3XBca3UioqmIA==,type:str]
    PGDATABASE: ENC[AES256_GCM,data:c4ZRzAOo6sc=,iv:pGC5em/EVx4RnHe0CFZtGj9U+bW0o0vvORUerU+2IP8=,tag:8/u9eq5EsjsAIA6YecfWQQ==,type:str]
    PGUSER: ENC[AES256_GCM,data:DvZxnnCk/Bk=,iv:TvfXCkkkS60FuxKHFQ4IOwlOxm2WPs8TCnWgxOagWlU=,tag:bxRqXs3ot+GdQKaVUyoERA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbkUwZUtoYjJmUjN3c3Ex
            c1AxNEQ2akdFMVNMYTBraGp4aU9Dc2lJVjI4CmZ4eTJrNnpXMXp2WjRVQVpGYlFh
            ZU8vODAzeWJ0dTJZZGpFcE1FWmdLSEEKLS0tIGpsVlU3WHJWSXFGMlRia01DbWwy
            bWhTdnFiUlJkd3JHZDJScmJRRkcwdHcK9whqNUuM7tak0hPtVHeP+Nc56FxFXTz1
            paOxWdiz//k8OQnd3xM5Ndo3TkkCqjnnx9JfaD1EANxUEfCqbdPokg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T06:29:45Z"
    mac: ENC[AES256_GCM,data:IG0S7hQW4ME0tCerFyLMEW0TVY43Ng3/r8E2y5a4jNjlfMA3cR2/KxObsZQvFQBd32JeMeO4QrwndrVdRInkVXQYMmzIVTzt8wifWnV5ufNHq2Ou52qv7P0QDFdOm/H8yFxZ1wFMA01y2pb3wvokG2ObLag6cq3rVNVbUwNS/sQ=,iv:9gI5EEF8nnlQaC3UX1LfGlUBWEDuQlpyGtSVpXrSdW8=,tag:qnJFyLkIdal0UgY5MFf3jA==,type:str]
    version: 3.13.3
