apiVersion: ENC[AES256_GCM,data:RcU=,iv:9iA1nJmk+cwYM/+0QaJarW6xQ5jnr4zFx1HukTi6DYs=,tag:ejkNwxL/K+0WmxWYQ3SUwg==,type:str]
kind: ENC[AES256_GCM,data:XJNLg1PA,iv:Koodk6B0y3G6CLiTBexcuwggmns2YiGzUQxXyFFSm2s=,tag:GVvOb69y/40KzMqORz5ERg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WRY7miOdY/ed3/Y=,iv:DxaJQDDFgykwmDnfidDFrJ/LkIT31u1oWQeEHHOw+sI=,tag:7jeSXw4YiPSbUDAbftKEdg==,type:str]
    namespace: ENC[AES256_GCM,data:eDelXhKkf/Y=,iv:aBV0qgKk58q8JHJ4saGEiXNWXo4mIu+NCo4ySsAQI/0=,tag:PgVsUhEoHu0ifEy4eyiBDw==,type:str]
type: ENC[AES256_GCM,data:oxmDaWxHLm9IYTvMSgolOa0tY6KOj5YxXrGKMDWP,iv:NE+UkQSUYnu3IEI8ZoZuS8BMpwztQ+T1522MFCKCnEI=,tag:VcCPcfLrGTcAjrgb04jOcA==,type:str]
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:D8oBeQ/qku2XPFB13wkNv5za5H9UVLBuy0NN9oWnozigFieyiWAuG0j3xAKHlNdPw8b3GX3vJMI3L9E2W5sL2LAjhQEoZ9lAnAF5XsRLphyB5xxBuIVVhpWChd/PT6X8q0TuXLd2oiFKR5FwbT6GS57eSiiS4xajqkt0eg/T8m11Ah7pbdhRHfnGQ2Dj0PHwcrRA+97EwU5BpM7pBXDLNiY+8S+o5Cq527/pPTvL147u0AM=,iv:TDssT1SS5z4lC94C8tBEtZYdA+phKDTwF2PyFPyOmPA=,tag:L4UUzDweTVv6YU0yxErkfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOXp4ZElNSEw0N09OdHhu
            eGZWVUd0SzJobFdpS0cwWXcrbER5K1NBQURrClpCTjl0RStVVWNqU3RmZzR0aXNH
            cEVra3FPWTdIK1hpUUZQTitmdGlTekkKLS0tIFQxRXI2cExNcUZtQk16R0pZNnZw
            S2tIMmpPQnlPOURoUzhsL0o3cEI1dFkKGqlodOKajhM1xhUJ/g6BmlNouqWS2bIc
            jIm8QDr2pcR0SXWMTHqizrIleMJtkEJP2Po9JFyOKtzzgE4P0ImVlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    lastmodified: "2026-09-23T10:20:45Z"
    mac: ENC[AES256_GCM,data:io3/oUwGC+jryCIun6MKmB+d2tFQmYrf9xXgBmx/sCTPOZLu8gxAJU0j3r+ix74xoQs4plpb8JeFKxGz3znYi6wZKpoRh+OCso+LL4qxM0kn4CDLsMcgiH36X9U/78H+flDGVa/IMdRWT1zHTptM9wYILOqySD6KnooaNrNeVJw=,iv:w6d+ptIf+BXyTJu95LvhXQActzWAvtiBbKIoKbZttZM=,tag:I86rrxue8X5F2cnNW0AeBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
