apiVersion: ENC[AES256_GCM,data:sV0=,iv:/i+RK22z8arvQoLX2sNSKN633/wbW27BYD3ethn7kuo=,tag:58U2SgjmAON7NZp4qvRZRw==,type:str]
kind: ENC[AES256_GCM,data:+yLHzUpF,iv:huGBJI70owS4bw78RcWV6daawYMkyEJzoOAzztctB2E=,tag:HKXxmLmrQph9lMa/oBMZUQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VLeDwEkTRYPc2dQ=,iv:rvso7pjqqSzonOQ3aUGZJyH0Qc8hkeXRUuYTAvNdlns=,tag:4hx9KoX9RDXQzaNNJqMv0Q==,type:str]
    namespace: ENC[AES256_GCM,data:4HjRf1x58Zw=,iv:t1ylJh9lcbYglT2L83gdXq9uFvxAEt88LddmdTwAMc4=,tag:vqPlnw6p+7KYjvU+K36vnQ==,type:str]
type: ENC[AES256_GCM,data:hFlUh7CHPdt35Ecm7LDYoJ3vXwe+RKWA/890F522,iv:xZBTgReAw8+WFHJ/1tnma1gMmZUCkr0xYcxPv7ZbKHw=,tag:QSVavNi7LQbI/o820wtUIQ==,type:str]
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:YjGlEXEMwMQS6eAHOROLY5sdkyDbescv2O3NwZI+YW9uLS6KCWTDebRRl8/G2HqFyxDj7JP0gokmHe5fkETeXhMK7UWImpYAecGgxWXzBx+drbx76mP47bCQy5sycKIjxkadYiGgpWpDoYuENSRHurDbZ+vfN/UcjbP2t+OWG5BacFDW40Fru8v2x5AW7FQ=,iv:a82jzkUNopnjgDC2ZOtx0ZH5baOX77LAgeht2wCjd4s=,tag:KIX6+sDN6yPpRV7482kgLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTjluOTJVRVp5V2U4V3Nv
            MEJHTmpPUmlUN0h4NW1EZWJXWUpMVEZ1WkM4CnBsdnM3WmNGVHRFTDZrRHdqc2tP
            QzRHL2xzd01kY2x5T014OFhINml3UlkKLS0tIHlKYWh6akdUMlJ0TTZPdHg2SUdq
            c2ZnZnZtWXhjV1M3ZDZlc2ZwRi9sc2MK9M8hYgkqvxUEKNBuixUhbpWS/OujYXzK
            fE1xfWt0gk6ENgujid2SYayxhx6qPcRT9U6i3FkFyZVJ5TRQolQEwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    lastmodified: "2026-09-23T10:26:12Z"
    mac: ENC[AES256_GCM,data:/vOAbJZkklzvmPITXBNEFrC9VvLQKI72+r2Qwvm8D89hDH6qV5/IG2XOzvLFgu5PVkx8JZ+UysuWD6MmCB15UtpnK3b+9AwSaAqW/E/MvJWnjclmfZUPv5NwmbHSWQy0MoXq3tYB2k8jsifpp5k14GzPOfN0vbt4c2fRtEqoUC8=,iv:v7yyHSiY9crx517NFZJxZHl4EnsVYB7lZhxmJwF1ldw=,tag:sXYzOhlCDN8t8ykDcNTDUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
