apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foodflow
resources:
  - foodflow-db-user.enc.yaml
  - foodflow-db-admin.enc.yaml
  - ghcr-secret.enc.yaml
  - foodflow-app-secrets.enc.yaml
